Lesson3 task5 right triangle
michalflis/firstMavenProject pull request #10
Opened 2021-06-30 16:57 UTC by michalflis

2021-06-30 20:39 UTC, radoslawdabrowski requested changes

2021-06-30 20:39 UTC, radoslawdabrowski commented on src/test/java/RightTriangleTest.java
> +    public void ShouldCheckIfTriangleWithSidesABCIsRight_3_4_5() {
Nazwy metod z małej litery :)

2021-06-30 20:39 UTC, radoslawdabrowski commented on src/test/java/RightTriangleTest.java
> +    public void ShouldCheckIfTriangleWithSidesABCIsNotRight_2_4_6() {
j.w

2021-06-30 20:39 UTC, radoslawdabrowski commented on src/test/java/RightTriangleTest.java
> +    RightTriangle rightTriangle = new RightTriangle(a, b, c);
zbędny obiekt - metoda, którą wykonujemy w testach jest statyczna, więc instancja klasy nie jest potrzebna

2021-07-01 15:47 UTC, michalflis commented on src/test/java/RightTriangleTest.java
> +    public void ShouldCheckIfTriangleWithSidesABCIsRight_3_4_5() {
Poprawione

2021-07-01 15:47 UTC, michalflis commented on src/test/java/RightTriangleTest.java
> +    public void ShouldCheckIfTriangleWithSidesABCIsNotRight_2_4_6() {
Poprawione

2021-07-01 15:47 UTC, michalflis commented on src/test/java/RightTriangleTest.java
> +    RightTriangle rightTriangle = new RightTriangle(a, b, c);
Poprawione

2021-07-02 06:37 UTC, mtszpater approved these changes

2021-07-02 17:58 UTC, merged