Task3 calculator
michalflis/firstMavenProject pull request #2
Opened 2021-06-24 20:13 UTC by michalflis

2021-06-24 20:30 UTC, radoslawdabrowski requested changes

2021-06-24 20:30 UTC, radoslawdabrowski commented on src/test/java/CalculatorTest.java
> +    public void ShouldAddSubtractTwoValues_10And3() {
Metoda powinna nosić nazwę```ShouldSubtractTwoValues_10And3```

2021-06-24 20:30 UTC, radoslawdabrowski commented on src/test/java/CalculatorTest.java
> +    public void ShouldAddMultiplyTwoValues_2And66() {
Metoda powinna nosić nazwę ```ShouldMultiplyTwoValues_2And66```

2021-06-24 20:30 UTC, radoslawdabrowski commented on src/test/java/CalculatorTest.java
> +    public void ShouldAddDivideTwoValues_0And7() {
Metoda powinna nosić nazwę ```ShouldDivideTwoValues_0And7```

2021-06-24 20:30 UTC, radoslawdabrowski commented on src/test/java/CalculatorTest.java
> +    public void ShouldAddDivideTwoValues_11And3() {
Metoda powinna nosić nazwe ```ShouldDivideTwoValues_11And3```

2021-06-24 21:14 UTC, michalflis commented on src/test/java/CalculatorTest.java
> +    public void ShouldAddSubtractTwoValues_10And3() {
Poprawione

2021-06-24 21:14 UTC, michalflis commented on src/test/java/CalculatorTest.java
> +    public void ShouldAddMultiplyTwoValues_2And66() {
Poprawione

2021-06-24 21:14 UTC, michalflis commented on src/test/java/CalculatorTest.java
> +    public void ShouldAddDivideTwoValues_0And7() {
Poprawione

2021-06-24 21:14 UTC, michalflis commented on src/test/java/CalculatorTest.java
> +    public void ShouldAddDivideTwoValues_11And3() {
Poprawione

2021-06-25 06:08 UTC, radoslawdabrowski approved these changes

2021-06-29 17:59 UTC, merged