Created CinemSeat class
michalflis/firstMavenProject pull request #6
Opened 2021-06-29 19:32 UTC by michalflis

2021-06-30 11:13 UTC, mtszpater commented on src/main/java/CinemaSeat.java
> +    boolean isTaken;
Czemu isTaken nie jest private, a cała reszta tak? ;) Skąd ta różnica?

+ aktualnie tego obiektu nie da się stworzyć, brakuje konstruktora.

2021-06-30 15:37 UTC, michalflis commented on src/main/java/CinemaSeat.java
> +    boolean isTaken;
seatNumber, i rowNumber mają być niezmienne dlatego są privat, będzie można je tylko stworzyć ale zmienić już nie. isTaken ma być edytowalne. Dodaem konstruktor

2021-06-30 20:34 UTC, radoslawdabrowski commented on src/main/java/CinemaSeat.java
> +    boolean isTaken;
Pola staraj się utrzymywać hermetycznie zamknięte (private) w przypadku kiedy chcesz udostępnić możliwość edycji wartości, stwórz metody set i get

2021-06-30 20:35 UTC, radoslawdabrowski commented on src/main/java/CinemaSeat.java
> +    boolean isTaken;
Dodatkowo, jeżeli chcemy aby pole nie było edytowalne dodajemy jeszcze jedno słówko kluczowe, o którym mówiłem na lekcji (`final`)

2021-06-30 20:36 UTC, radoslawdabrowski requested changes
Odpisałem w wątku co jest jeszcze nie tak

2021-07-01 15:48 UTC, michalflis commented on src/main/java/CinemaSeat.java
> +    boolean isTaken;
poprawione

2021-07-02 06:29 UTC, mtszpater approved these changes

2021-07-02 17:58 UTC, merged